#ifndef BOOST_FAIRNESS_CONFIG_HPP
#define BOOST_FAIRNESS_CONFIG_HPP
#ifdef BOOST_FOUND
#include <boost/atomic.hpp>
#endif
#if defined(BOOST_ATOMIC_INT128_LOCK_FREE) && BOOST_ATOMIC_INT128_LOCK_FREE > 0
#define BOOST_FAIRNESS_HAS_DWCAS
#endif
#endif // BOOST_FAIRNESS_CONFIG_HPP